apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-example'
  labels:
    katenary.io/component: example
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: c265932916d77cf2558b955160ca3d83c9eed7a7
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: example
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: example
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: example
          image: '{{ .Values.example.repository.image }}{{ if ne .Values.example.repository.tag "" }}:{{ .Values.example.repository.tag }}{{ end }}'
          ports:
            - name: example
              containerPort: 4000

